import { z } from 'genkit';
import { ai } from '@/backend/ai/core/config/genkit.config';
import { getGeminiClient } from '@/backend/ai/core/infrastructure/gemini-client';

const RenderInputSchema = z.object({
    imageBuffers: z.array(z.string()).describe("Base64 encoded images"),
    style: z.string(),
    roomType: z.string(),
    additionalRequirements: z.string().optional()
});

const RenderOutputSchema = z.object({
    generatedImage: z.string().describe("Base64 encoded generated image"),
});

/**
 * Builds the renovation prompt text directly.
 */
function buildPromptText(input: { style: string; roomType: string; additionalRequirements?: string }): string {
    let prompt = `Transform the attached photograph of a ${input.roomType} into a ${input.style} style renovation.

Instructions:
1. Preserve the architectural structure, windows, ceiling height, and perspective of the original room (ControlNet-like structural integrity).
2. Update the materials (flooring, walls, ceiling) to match the ${input.style} aesthetic.
3. Replace or update the furniture to fit the ${input.style} design language.
4. Adjust lighting to be natural and photorealistic.`;

    if (input.additionalRequirements) {
        prompt += `

Additional Client Requirements:
${input.additionalRequirements}`;
    }

    prompt += `

Output: A high-quality, photorealistic architectural rendering.`;

    return prompt;
}

export const generateRenderFlow = ai.defineFlow(
    {
        name: 'generateRenderFlow',
        inputSchema: RenderInputSchema,
        outputSchema: RenderOutputSchema,
    },
    async (input) => {
        const client = getGeminiClient();

        // 1. Build prompt text directly
        const promptText = buildPromptText({
            style: input.style,
            roomType: input.roomType,
            additionalRequirements: input.additionalRequirements,
        });

        // 2. Prepare image parts
        const imageParts = input.imageBuffers.map(buffer => ({
            inlineData: {
                data: buffer,
                mimeType: "image/jpeg"
            }
        }));

        // 3. Call Gemini via Vertex AI (no geo-restrictions)
        const response = await client.models.generateContent({
            model: "gemini-2.0-flash-preview-image-generation",
            contents: [
                { role: 'user', parts: [{ text: promptText }, ...imageParts] }
            ],
            config: {
                responseModalities: ['IMAGE'],
            }
        });

        const candidate = response.candidates?.[0];
        const generatedPart = candidate?.content?.parts?.find((p: any) => p.inlineData);

        if (!generatedPart?.inlineData?.data) {
            throw new Error("No image generated by Gemini or missing inlineData");
        }

        return {
            generatedImage: generatedPart.inlineData.data
        };
    }
);
