from typing import Dict, Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime
import uuid

class TelemetryEvent(BaseModel):
    """
    Core Domain Entity representing a single, ephemeral telemetry event
    generated by an asynchronous pipeline job (e.g. AI Extraction).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    job_id: str
    event_type: str
    data: Dict[str, Any]
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
