import { genkit, z } from 'genkit';
import { ai } from '@/backend/ai/shared/config/genkit.config';
import { getGeminiClient } from '@/backend/ai/infrastructure/gemini-client';

const RenderInputSchema = z.object({
    imageBuffer: z.string().describe("Base64 encoded image"),
    style: z.string(),
    roomType: z.string(),
    additionalRequirements: z.string().optional(),
    aspectRatio: z.string().describe("1:1, 3:4, 4:3, 9:16, or 16:9").optional().default("16:9")
});

const RenderOutputSchema = z.object({
    generatedImage: z.string().describe("Base64 encoded generated image"),
    appliedPrompt: z.string().describe("The exact final prompt used"),
});

export const generateRenderFlow = ai.defineFlow(
    {
        name: 'generateRenderFlow',
        inputSchema: RenderInputSchema,
        outputSchema: RenderOutputSchema,
    },
    async (input) => {
        const client = getGeminiClient();

        // 1. Render the text prompt using the .prompt file architecture
        // We use the Genkit prompt reference to separate prompt logic from code.
        const renovationPrompt = ai.prompt('renovation-render');

        // We render the prompt template to text
        const rendered = await renovationPrompt.render({
            style: input.style,
            roomType: input.roomType,
            additionalRequirements: input.additionalRequirements,
        });

        // Extract the text content from the rendered prompt
        // Use optional chaining for safety as 'messages' might be undefined in some Genkit versions/contexts
        let basePromptText = rendered.messages?.[0]?.content.find(c => c.text)?.text || '';

        if (!basePromptText) {
            throw new Error("Failed to render prompt text from renovation-render.prompt: No text content generated.");
        }

        let finalPrompt = basePromptText;
        
        // AUTO-PROMPTING with Gemini 2.5 Flash (Translator/Enhancer)
        // Taking the simplistic user intention and blowing it up into a master prompt
        const promptTranslatorResponse = await client.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{
                role: 'user', 
                parts: [{ text: `Actúa como un director de arte arquitectónico experto en prompts para motores fotorealistas como Midjourney v6 y Vertex Imagen 3. 
Tengo las siguientes intenciones básicas de un cliente para reformar su ${input.roomType}:
- Estilo: ${input.style}
- Requisitos extra: ${input.additionalRequirements || 'Ninguno'}

Redacta UN SOLO prompt en inglés, enormemente descriptivo, enfocado en la fotorrealidad, iluminación natural volumétrica, texturas de materiales de alta calidad, renderizado arquitectónico profesional (vray, octane render).
DEBES mantener la estructura estructural de la habitación intacta.
Devuelve ÚNICAMENTE el texto en inglés del prompt sin comentarios ni comillas.`}]
            }]
        });
        
        const promptCandidate = promptTranslatorResponse.candidates?.[0];
        const textPart = promptCandidate?.content?.parts?.find(p => p.text);
        if (textPart?.text) {
            finalPrompt = textPart.text;
            console.log("[Prompt Master] Enhanced Image Prompt:", finalPrompt);
        }

        // 2. Prepare the payload for the Generative Image Model
        const imagePart = {
            inlineData: {
                data: input.imageBuffer,
                mimeType: "image/jpeg"
            }
        };

        // 3. Call the model
        const aspectRatioVal = input.aspectRatio || "16:9";

        const response = await client.models.generateContent({
            model: "gemini-2.5-flash-image",
            contents: [
                { role: 'user', parts: [{ text: finalPrompt }, imagePart] }
            ],
            config: {
                responseModalities: ['IMAGE'],
                systemInstruction: `Return the image strictly in aspect ratio: ${aspectRatioVal}`
            }
        });

        const candidate = response.candidates?.[0];
        const generatedPart = candidate?.content?.parts?.find(p => p.inlineData);

        // Fix TypeScript Error: Ensure we return string, not undefined
        if (!generatedPart?.inlineData?.data) {
            throw new Error("No image generated by Gemini or missing inlineData");
        }

        return {
            generatedImage: generatedPart.inlineData.data,
            appliedPrompt: finalPrompt
        };
    }
);
